### ISSUE TITLE
Import package not found: github.com/goplus/gop/builtin/ng

### ISSUE THREAD

**Issue by XiongUp** [goplus/gop#1161]
### The following program `sample.gop` triggers an unexpected result

```coffee
println [1, 2, 3.4]
```

### Expected result

```console
[1, 2, 3.4]
```

### Got

```console
(cvlab) root@7c8a9f63a67f:/dev/shm/go_projects# gop run test.gop
2022/04/26 15:25:36 Import package not found: github.com/goplus/gop/builtin/ng
panic: Import package not found: github.com/goplus/gop/builtin/ng


goroutine 1 [running]:
log.Panicln({0xc0001518d8, 0x20, 0x20})
        /usr/local/go/src/log/log.go:368 +0x65
github.com/goplus/gox.(*PkgRef).EnsureImported(0xc00007f630)
        /root/go/pkg/mod/github.com/goplus/gox@v1.10.8/import.go:96 +0xc8
github.com/goplus/gop/cl.initMathBig({0x0, 0x779633}, 0xc0000744e0, 0x0)
        /root/gop/cl/builtin.go:29 +0x2a
github.com/goplus/gop/cl.newBuiltinDefault({0x7e6260, 0xc00013a200}, 0x7788fa)
        /root/gop/cl/builtin.go:64 +0xef
github.com/goplus/gox.NewPackage({0x0, 0xc000072400}, {0x7788fa, 0x4}, 0xc00001efc0)
        /root/go/pkg/mod/github.com/goplus/gox@v1.10.8/package.go:284 +0x37d
github.com/goplus/gop/cl.NewPackage({0x0, 0x0}, 0xc00001ef90, 0xc000151cc0)
        /root/gop/cl/compile.go:373 +0x329
github.com/goplus/gop/x/gopproj.(*gopFiles).GenGo(0xc000072320, {0x77ba7a, 0x9e7400}, {0xc0000301a0, 0x1b})
        /root/gop/x/gopproj/gopfiles.go:131 +0x433
github.com/goplus/gop/x/gopproj.(*Context).GoCommand(0xc00001e1a0, {0x778673, 0x3}, 0xc000122850)
        /root/gop/x/gopproj/projctx.go:94 +0x213
github.com/goplus/gop/cmd/internal/run.gopRun({0xc00001e1a0, 0xc00001e1a0, 0x509818})
        /root/gop/cmd/internal/run/run.go:105 +0x288
github.com/goplus/gop/cmd/internal/run.runCmd(0xc000074180, {0xc00001e1a0, 0x11, 0xc000052730})
        /root/gop/cmd/internal/run/run.go:63 +0xc5
main.main()
        /root/gop/cmd/gop/main.go:108 +0x4df
```

### Gop Version

Release v1.1.0-beta3

### Additional Notes

I install Go+ from source code.
```
(cvlab) root@7c8a9f63a67f:~# cd gop
(cvlab) root@7c8a9f63a67f:~/gop# ./all.bash
+ go run cmd/make.go --install --autoproxy
Installing Go+ tools...

Start Linking.
Link /root/gop/bin/gop to /root/go/bin/gop successfully.
Link /root/gop/bin/gopfmt to /root/go/bin/gopfmt successfully.
End linking.

Go+ tools installed successfully!
```

**Comment by xushiwei** [comment]
It seems the reason is there are old version go.mod in ~/.gop/run directory.

You can try to `rm -rf ~/.gop` to avoid this problem.

**Comment by XiongUp** [comment]
Thanks for your reply.
There seem no ~/. gop in my computer, I can't find it.
May you mean ~/gop?

**Comment by xushiwei** [comment]
No. It means $HOME/.gop

**Comment by XiongUp** [comment]
But it doesn't exist.
```
(base) root@7c8a9f63a67f:~# cd $HOME/.gop
bash: cd: /root/.gop: No such file or directory
```

**Comment by xushiwei** [comment]
Well, you may temporarily create a go.mod to avoid this problem:

* go mod init `your_app_name`
* go get github.com/goplus/gop@v1.1.0-beta3
* gop run test.gop

**Comment by XiongUp** [comment]
Thanks. It solves the problem.
