### ISSUE TITLE
go plus is unable to find certain go librarys.

### ISSUE THREAD

**Issue by lolbinarycat** [goplus/gop#411]
I'll give the example of the fyne.io readme demo:
```go
package main

import (
	   "fyne.io/fyne/widget"
	   "fyen.io/fyne/app"
)

func main() {
	app := app.New()

	w := app.NewWindow("Hello")
	w.SetContent(widget.NewVBox(
		widget.NewLabel("Hello Fyne!"),
		widget.NewButton("Quit", func() {
			app.Quit()
		}),
	))

	w.ShowAndRun()
}
```
running this gives:
```
ReadDir failed: readdirent: not a directory
binarycat@laptop:~/github-go/kibi$ qrun main.gop
[PANIC] github.com/qiniu/goplus/cl/expr.go:163: compileIdent failed: package not found - fyen.io/fyne/app
panic: compileIdent failed: package not found - fyen.io/fyne/app


goroutine 1 [running]:
github.com/qiniu/x/log.Panicln(0xc0001155e0, 0x2, 0x2)
        /home/binarycat/go/pkg/mod/github.com/qiniu/x@v1.10.5/log/logext.go:544 +0xbd
github.com/qiniu/goplus/cl.compileIdent(0xc00009b500, 0xc0000b8187, 0x3, 0x118)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/expr.go:163 +0x7e5
github.com/qiniu/goplus/cl.compileExpr(0xc00009b500, 0x7395e0, 0xc0000ae800, 0x1)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/expr.go:57 +0x133
github.com/qiniu/goplus/cl.compileSelectorExpr(0xc00009b500, 0xc0000ae840, 0xa0)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/expr.go:891 +0x5c
github.com/qiniu/goplus/cl.compileExpr(0xc00009b500, 0x7399a0, 0xc0000ae840, 0xc000098620)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/expr.go:67 +0x43a
github.com/qiniu/goplus/cl.compileCallExpr(0xc00009b500, 0xc0000c0540, 0x3a98753f)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/expr.go:609 +0x59
github.com/qiniu/goplus/cl.compileExpr(0xc00009b500, 0x739160, 0xc0000c0540, 0x8)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/expr.go:61 +0x378
github.com/qiniu/goplus/cl.compileAssignStmt(0xc00009b500, 0xc0000c0580)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/stmt.go:393 +0x2ca
github.com/qiniu/goplus/cl.compileStmt(0xc00009b500, 0x738f60, 0xc0000c0580)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/stmt.go:53 +0x445
github.com/qiniu/goplus/cl.compileBlockStmtWithout(0xc00009b500, 0xc00009b260)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/stmt.go:36 +0x70
github.com/qiniu/goplus/cl.(*FuncDecl).Compile(0xc00009b560, 0xc0000bc078, 0xc00009b3e0)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/type_decl.go:341 +0x112
github.com/qiniu/goplus/cl.(*pkgCtx).resolveFuncs(0xc0000e6070)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/compile.go:146 +0x34
github.com/qiniu/goplus/cl.NewPackage(0x73be20, 0xc00009b3e0, 0xc00009b320, 0xc0000c0180, 0x1, 0xc00009b2c0, 0x0, 0x0)
        /home/binarycat/go/src/github.com/qiniu/goplus/cl/compile.go:519 +0x398
main.main()
        /home/binarycat/go/src/github.com/qiniu/goplus/cmd/qrun/qrun.go:74 +0x41c
```

Something similar happens to me basicaly every time I try to use go+.

**Comment by xushiwei** [comment]
Not implemented.
See https://github.com/qiniu/goplus/issues/378

**Comment by xushiwei** [comment]
Related issue: https://github.com/goplus/gop/issues/472

* Support export Github packages.
* Support export GoPlus src packages.

See #473
See https://github.com/goplus/gop/wiki/Import-Go-packages-in-GoPlus-programs
