### ISSUE TITLE
os.Stdout doesn't work

### ISSUE THREAD

**Issue by skyjia** [goplus/gop#419]
```gop
import (
    "log"
    "os"
)

log.Println("hello", true)

logger := log.New(os.Stdout, "logger: ", log.Lshortfile)
logger.Println("foo","bar", false, 666)
```

I tried to qrun the script above, but got such error:

```sh
[PANIC] /Users/skyjia/Workspace/skyjia@GitHub/goplus/cl/expr.go:915: compileSelectorExpr: unknown GoPackage symbol kind - 0
panic: compileSelectorExpr: unknown GoPackage symbol kind - 0


goroutine 1 [running]:
github.com/qiniu/x/log.Panicln(0xc00015b9a8, 0x2, 0x2)
        /Users/skyjia/go/pkg/mod/github.com/qiniu/x@v1.10.5/log/logext.go:544 +0xbd
github.com/qiniu/goplus/cl.compileSelectorExpr(0xc000067290, 0xc00000c660, 0x1)
        /Users/skyjia/Workspace/skyjia@GitHub/goplus/cl/expr.go:915 +0x742
github.com/qiniu/goplus/cl.compileExpr(0xc000067290, 0x1344340, 0xc00000c660, 0xc000067290)
        /Users/skyjia/Workspace/skyjia@GitHub/goplus/cl/expr.go:67 +0x43a
github.com/qiniu/goplus/cl.compileCallExpr.func2()
        /Users/skyjia/Workspace/skyjia@GitHub/goplus/cl/expr.go:635 +0xce
github.com/qiniu/goplus/cl.compileAssignStmt(0xc000067290, 0xc000026480)
        /Users/skyjia/Workspace/skyjia@GitHub/goplus/cl/stmt.go:437 +0x2d4
github.com/qiniu/goplus/cl.compileStmt(0xc000067290, 0x1343900, 0xc000026480)
        /Users/skyjia/Workspace/skyjia@GitHub/goplus/cl/stmt.go:53 +0x445
github.com/qiniu/goplus/cl.compileBlockStmtWithout(0xc000067290, 0xc000067050)
        /Users/skyjia/Workspace/skyjia@GitHub/goplus/cl/stmt.go:36 +0x70
github.com/qiniu/goplus/cl.NewPackage(0x1346b00, 0xc0000671d0, 0xc000067110, 0xc0000261c0, 0x1, 0xc0000670b0, 0x0, 0x0)
        /Users/skyjia/Workspace/skyjia@GitHub/goplus/cl/compile.go:555 +0x4f7
main.main()
        /Users/skyjia/Workspace/skyjia@GitHub/goplus/cmd/qrun/qrun.go:74 +0x41c
```

It panics when calling `os.Stdout`.

**Comment by xushiwei** [comment]
This is because using a `pkg.var` is not implemented - https://github.com/goplus/gop/blob/master/cl/expr.go#L915
I add a related testcase - https://github.com/goplus/gop/pull/423/files
assign to @visualfc

**Comment by xushiwei** [comment]
Does https://github.com/goplus/gop/pull/293 fix this bug?

**Comment by visualfc** [comment]
fixed, output

gop run .
``` 
2020/07/13 08:35:35 hello true
logger: gomod_export.go:203: foo bar false 666
```

qgo go .
```
package main

import (
	log "log"
	os "os"
)

var logger *log.Logger

func main() {
//line ./main.gop:6
	log.Println("hello", true)
//line ./main.gop:8
	logger = log.New(os.Stdout, "logger: ", 16)
//line ./main.gop:9
	(*log.Logger).Println(logger, "foo", "bar", false, int64(666))
}
```

**Comment by xushiwei** [comment]
cool
