### ISSUE TITLE
Supports the compilation of external types under compositelit

### ISSUE THREAD

**Issue by go-wyvern** [goplus/gop#491]
When I tested goroutine, sync.Waitgroup found out that we currently do not support the compilation of external types under compositelit. so the first step I need to support the compilation of external types

```
wg := sync.WaitGroup{}
```

Panic appeared

```
panic: toExternalType: todo

goroutine 1 [running]:
github.com/goplus/gop/cl.toExternalType(...)
        /Users/wuxinyi/go/src/github.com/goplus/gop/cl/type_decl.go:229
github.com/goplus/gop/cl.toType(0xc00001fd10, 0x15fbe40, 0xc00000c640, 0x110, 0xc000106ea0)
        /Users/wuxinyi/go/src/github.com/goplus/gop/cl/type_decl.go:66 +0x392
github.com/goplus/gop/cl.compileCompositeLit(0xc00001fd10, 0xc00007e640, 0xc00001fc80)
        /Users/wuxinyi/go/src/github.com/goplus/gop/cl/expr.go:233 +0x62
github.com/goplus/gop/cl.compileExpr(0xc00001fd10, 0x15fb700, 0xc00007e640, 0x4)
        /Users/wuxinyi/go/src/github.com/goplus/gop/cl/expr.go:80 +0x187
github.com/goplus/gop/cl.compileAssignStmt(0xc00001fd10, 0xc00007e680)
        /Users/wuxinyi/go/src/github.com/goplus/gop/cl/stmt.go:627 +0x2ca
github.com/goplus/gop/cl.compileStmt(0xc00001fd10, 0x15fb400, 0xc00007e680)
```

**Comment by xushiwei** [comment]
https://github.com/goplus/gop/pull/557
