### ISSUE TITLE
user-defined struct cannot support  unexported field

### ISSUE THREAD

**Issue by visualfc** [goplus/gop#558]
Go+ code
```
 type M struct {
	x int
	y int
}
&M{10,20}
```

```
panic: reflect.StructOf: field "x" is unexported but missing PkgPath

goroutine 1 [running]:
reflect.runtimeStructField(0x47e1558, 0x1, 0x0, 0x0, 0x45ae7e0, 0x43933e0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/type.go:2769 +0x1df
reflect.StructOf(0xc00025c1a0, 0x2, 0x2, 0x0, 0x0)
	/usr/local/go/src/reflect/type.go:2385 +0x1e3f
...
```

**Comment by go-wyvern** [comment]
i see, If the field cannot be accessed externally, StructOf needs to bring PkgPath, but the current package management of Go+ is not sure which method to use, so how to get the value of this PkgPath is still a problem
