### ISSUE TITLE
go run main.go 可以执行， gop run main.go 报错  [PANIC] /Users/z/git/gop/cl/expr.go:179: compileIdent failed: package not found - github.com/nknorg/nkn-sdk-go

### ISSUE THREAD

**Issue by gcxfd** [goplus/gop#562]
![image](https://user-images.githubusercontent.com/69608605/90718192-e5424300-e2e3-11ea-9bd5-c06efdff762c.png)

❯ go run main.go
```
0xc000164000
Hello, Go+
```
❯ gop run main.go
```
[PANIC] /Users/z/git/gop/cl/expr.go:179: compileIdent failed: package not found - github.com/nknorg/nkn-sdk-go
panic: compileIdent failed: package not found - github.com/nknorg/nkn-sdk-go


goroutine 1 [running]:
github.com/qiniu/x/log.Panicln(0xc00018f5b8, 0x2, 0x2)
        /Users/z/go/pkg/mod/github.com/qiniu/x@v1.11.5/log/logext.go:544 +0xbf
github.com/goplus/gop/cl.compileIdent(0xc000066600, 0xc000024660, 0x3, 0xd0)
        /Users/z/git/gop/cl/expr.go:179 +0x7fd
github.com/goplus/gop/cl.compileExpr(0xc000066600, 0x15bb860, 0xc00000c920, 0xc00018f6f8)
        /Users/z/git/gop/cl/expr.go:59 +0x9d
github.com/goplus/gop/cl.compileSelectorExpr(0xc000066600, 0xc00000c960, 0x1955900, 0xc0001aa120)
        /Users/z/git/gop/cl/expr.go:1101 +0x5c
github.com/goplus/gop/cl.compileCallExpr(0xc000066600, 0xc000032880, 0x0, 0x256cb50797e40e01)
        /Users/z/git/gop/cl/expr.go:681 +0x5f
github.com/goplus/gop/cl.compileExpr(0xc000066600, 0x15bb3e0, 0xc000032880, 0x8)
        /Users/z/git/gop/cl/expr.go:63 +0x366
github.com/goplus/gop/cl.compileAssignStmt(0xc000066600, 0xc0000328c0)
        /Users/z/git/gop/cl/stmt.go:488 +0x2e5
github.com/goplus/gop/cl.compileStmt(0xc000066600, 0x15bb1e0, 0xc0000328c0)
        /Users/z/git/gop/cl/stmt.go:59 +0x4a6
github.com/goplus/gop/cl.compileBlockStmtWithout(0xc000066600, 0xc00001fe00)
        /Users/z/git/gop/cl/stmt.go:36 +0x74
github.com/goplus/gop/cl.(*FuncDecl).Compile(0xc000032ac0, 0xc00000e0c0, 0xc00001ff80)
        /Users/z/git/gop/cl/type_decl.go:407 +0x117
github.com/goplus/gop/cl.(*pkgCtx).resolveFuncs(0xc000116080)
        /Users/z/git/gop/cl/context.go:84 +0x34
github.com/goplus/gop/cl.NewPackage(0x15c42e0, 0xc00001ff80, 0xc00001fec0, 0xc000032540, 0x1, 0x0, 0xc00001fe60, 0x0)
        /Users/z/git/gop/cl/compile.go:200 +0x3b3
github.com/goplus/gop/cmd/internal/run.runCmd(0x1806020, 0xc00001e1d0, 0x1, 0x1)
        /Users/z/git/gop/cmd/internal/run/run.go:88 +0x425
main.main()
        /Users/z/git/gop/cmd/gop/main.go:72 +0x20b
~/rmw-link/srv/gop master
```

代码
```
package main

import (
        nkn "github.com/nknorg/nkn-sdk-go"
)

func main() {
        account, _ := nkn.NewAccount(nil)
        client, _ := nkn.NewClient(account, "", nil)

        println(client)
        println("Hello, Go+")

}
```

**Comment by xushiwei** [comment]
`import` is not implemented. See https://github.com/goplus/gop/issues/378.
